import json
from openai import OpenAI
import os
from bart_score import BARTScorer
os.environ["http_proxy"] = "http://localhost:7890"
os.environ["https_proxy"] = "http://localhost:7890"

#select a threshold
threshold = None

key= "" #openai_key
client = OpenAI(api_key=key)

data = input()
revised_data = ""
stream = client.chat.completions.create(
    model="gpt-4-turbo-0125",
    messages=[{"role": "user", "content": f"Revise the following text: {data}"}],
    stream=True
)
temp=""
for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        temp = temp+chunk.choices[0].delta.content
revised_data = temp

bartscorer = BARTScorer(device='cuda:0',checkpoint="facebook/bart-large-cnn")

score = bartscorer.score([temp],[data])

if score > threshold:
    print("This sentence is most probably generated by AI")
else:
    print("This sentence is most probably written by humans")



